### ISSUE TITLE
Invalid tide directory

### ISSUE THREAD

**Issue by lucas-langlois** [GeoscienceAustralia/dea-intertidal#35]
Hi,

I'm trying to run your Intertidal elevation notebook and I am running into an issue relating to the tide directory. Would you be able to help?

See the error code below.

Thank you very much

Lucas Langlois

FileNotFoundError                         Traceback (most recent call last)
Cell In[14], line 5
      1 if tide_model == "ensemble":
      2     # Model tides into every pixel in the three-dimensional satellite
      3     # dataset (x by y by time) after generating ensemble model using
      4     # ancillary inputs
----> 5     tide_m, model_weights = pixel_tides_ensemble(
      6         satellite_ds,
      7         directory=tide_model_dir,
      8         ancillary_points="data/raw/corr_points.geojson",
      9     )
     11     # Print models in order of correlation
     12     print(
     13         model_weights.mean(dim=["x", "y"])
     14         .to_dataframe("correlation")
     15         .sort_values("correlation", ascending=False)
     16     )

File ~/DEA-inter_main/notebooks/intertidal/elevation.py:555, in pixel_tides_ensemble(satellite_ds, directory, ancillary_points, top_n, models, interp_method)
    543     models = [
    544         "FES2014",
    545         "FES2012",
   (...)
    550         "GOT4.10",
    551     ]
    553 # Model tides into every pixel in the three-dimensional
    554 # (x by y by time) satellite dataset
--> 555 tide_lowres = pixel_tides(
    556     satellite_ds,
    557     resample=False,
    558     model=models,
    559     directory=directory,
    560 )
    562 # Load ancillary points from file, reproject to match satellite
    563 # data, and drop empty points
    564 print("Generating ensemble tide model from point inputs")

File /env/lib/python3.10/site-packages/dea_tools/coastal.py:1020, in pixel_tides(ds, times, resample, calculate_quantiles, resolution, buffer, resample_method, model, dask_chunks, dask_compute, **model_tides_kwargs)
   1017 flattened_ds = flattened_ds.expand_dims(dim={"time": time_coords.values})
   1019 # Model tides in parallel, returning a pandas.DataFrame
-> 1020 tide_df = model_tides(
   1021     x=flattened_ds[x_dim],
   1022     y=flattened_ds[y_dim],
   1023     time=flattened_ds.time,
   1024     crs=f"EPSG:{ds.odc.geobox.crs.epsg}",
   1025     model=model,
   1026     **model_tides_kwargs,
   1027 )
   1029 # Convert our pandas.DataFrame tide modelling outputs to xarray
   1030 tides_lowres = (
   1031     # Rename x and y dataframe indexes to match x and y xarray dims
   1032     tide_df.rename_axis(["time", x_dim, y_dim])
   (...)
   1041     .transpose("tide_model", "time", y_dim, x_dim)
   1042 )

File /env/lib/python3.10/site-packages/dea_tools/coastal.py:575, in model_tides(x, y, time, model, directory, crs, method, extrapolate, cutoff, mode, parallel, parallel_splits, output_units, output_format, epsg)
    573 directory = pathlib.Path(directory).expanduser()
    574 if not directory.exists():
--> 575     raise FileNotFoundError("Invalid tide directory")
    577 # If time passed as a single Timestamp, convert to datetime64
    578 if isinstance(time, pd.Timestamp):

FileNotFoundError: Invalid tide directory

**Comment by robbibt** [comment]
Hey @lucas-langlois! Great to hear from you - to be honest, the code in this repo is very much a work in progress, and we didn't expect anyone to be using it yet. Are you planning to run this in Australia, e.g. on the DEA Sandbox? Or somewhere global? 

Basically, although you're welcome to try out the code if you like, there's no guarentee that any of the code here works correctly at the moment - we'll be officially publishing this code and adding useful documentation closer to the product release early next year. 

The specific error you've posted is because you don't have access to the tide modelling files required for the analysis. Are you trying to run this in Australia (e.g. on the DEA Sandbox) or somewhere global? If it's the Australia/on the DEA Sandbox, you should be able to set the `tide_model_dir` to `None` and it should find the right files automatically.

Otherwise, you'll need to follow this guide here to sign up to AVISO+ and download the FES2014 tide model files *(https://github.com/GeoscienceAustralia/dea-coastlines/wiki/Setting-up-tidal-models-for-DEA-Coastlines). Once you've done that, set `tide_model_dir` to the location you've saved your files (e.g. `"/tide_models/"` or similar). 

The "ensemble" tide modelling functionality is very experimental - you'll need to set `tide_model` to `"FES2014"` for now regardless of where you run the code. 🙂

**Comment by robbibt** [comment]
For now, there's also an easier to use workflow available pre-installed in our DEA Notebooks repository - it's an older method, but it should still produce useful results: https://docs.dea.ga.gov.au/notebooks/Real_world_examples/Intertidal_elevation.html

**Comment by lucas-langlois** [comment]
Hi @robbibt,

Thanks for the answer. I am working on the GBR and have been using the ITEM layers for one of our project. But this product falls short in quite a few places at the moment. So I was keen to try using your new the per pixel tide elevation calculation and the sentinel imagery to see if that will make some significant improvements in our reef habitats. 
Would the product release you mentioned would include the ITEM update ? Would you have a rough date for that ? If so I might not need to run the code at all.

Thank you very much

**Comment by robbibt** [comment]
The new products will include intertidal elevation, intertidal exposure (% of time each pixel is inundated/exposed by tides) and intertidal extents (extents of the exposed portion of the intertidal zone, excluding vegetation like mangroves). So it will be a bit different from ITEM/NIDEM, but hopefully much more detailed and useful. 

For the GBR, you may still run into issues with Landsat/Sentinel-2 data not capturing the most extreme low and high tides - this isn't something we can fix unfortunately (the satellite overpass time means those tides are simply never imaged). But we will be including new metadata that will at least help better map out those kinds of biases.

The release is currently planned for March next year, but it hasn't been locked down yet. If you shoot me an email I can make sure you get notified about the release? Robbi.BishopTaylor@ga.gov.au
